### ISSUE TITLE
PatentTransformer_v2 module - model import error

### ISSUE THREAD

**Issue by ddofer** [jiehsheng/PatentTransformer#1]
I'm getting an error trying to run the v2 patent ipython notebook,
"import model, sample, encoder" - results in an error, No module named 'model' - what is meant to be imported at this step?
Thanks!

**Comment by leejason** [comment]
The step is to import the required files cloned from https://github.com/openai/gpt-2/tree/master/src.

 I just tested the notebook without any error. Could you try "Run all" again?

**Comment by ddofer** [comment]
I had to change gthe relative file paths for the os.chdir's , as they were giving errors. I had changed to the gpt-2 dir after downloading it. I'll try to debug. Replication of the bug would be to run it on an new computer. Mayhaps linux vs OSX?

**Comment by ddofer** [comment]
Changing the firectory manually to gpt2/src fixes the imports. That said, other bits in the notebook fail due to issues with relative directory paths. (e.g. it needs manually hacking in things like "./gpt2" vs "/gpt2" vs "../gpt2" etc' )

**Comment by jiehsheng** [comment]
The notebook is for running on Colab. Could you try it there instead?
