### ISSUE TITLE
Details on encoder, bpe file and TPU pod type

### ISSUE THREAD

**Issue by manueltonneau** [jiehsheng/PatentTransformer#2]
Hi guys,

I stumbled upon your paper and it's a very cool idea for a GPT-2 usecase.
I saw you mentioned in the paper you used [this implementation](https://github.com/ConnorJL/GPT2) to train the model.

I have a question regarding the `encoder.json` file: did you generate your own? If so, how? (linked with [this issue](https://github.com/ConnorJL/GPT2/issues/27)). 
For the vocabulary, could you mention the library you used to create the bpe file? SentencePiece?

Finally, could you mention the type of TPU pod you used for training?

Thanks a lot in advance.

**Comment by jiehsheng** [comment]
>  encoder.json file: did you generate your own?
> vocabulary

No. I use only what provided in the original GPT-2 by OpenAI. As for TPU, I use Colab.

**Comment by manueltonneau** [comment]
Ok thanks for your reply!
